package Formularios;

import Controler.ControladorLogin;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class FrmContraseña extends javax.swing.JFrame {
    ControladorLogin ControladorLogin;
    /**
     * Creates new form FrmContraseña
     */
    public FrmContraseña() {
        initComponents();
        
        Model.Usuario usuarioLogueado = Model.SesionUsuario.getInstancia().getUsuarioLogueado();
        if (usuarioLogueado != null) {      
        // 3. Extraemos los datos que guardó el DAO            
            int idUser = usuarioLogueado.getId_usuario();
            String nombreRol = usuarioLogueado.getNombre_rol();
            String nombreUsuario = usuarioLogueado.getUsername();
            
            txtUsuario.setText(idUser+"");
            txtRol.setText(nombreRol);  
            txtNombreUsuario.setText(nombreUsuario);
        }    
        
        // Asignamos el listener a los dos campos de texto
        txtContra.getDocument().addDocumentListener(listenerPassword);
        txtConfirmarContra.getDocument().addDocumentListener(listenerPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        txtConfirmarContra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMensajePassword = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("N° USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("NOMBRE DE USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CONFIRMAR CONTRASEÑA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("TIPO DE ROL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtUsuario.setEnabled(false);
        txtUsuario.setFocusCycleRoot(true);
        txtUsuario.setFocusable(false);
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, -1));

        txtRol.setEnabled(false);
        txtRol.setFocusCycleRoot(true);
        txtRol.setFocusable(false);
        getContentPane().add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, -1));
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 200, -1));
        getContentPane().add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, -1));
        getContentPane().add(txtConfirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 200, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario_1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 70, 70));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblMensajePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 244, 189, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 220, 260));

        btnActualizar.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 30));

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 90, 30));

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 90, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("PERFIL DE USUARIO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //evento DocumentListener para validar la contraseña
    DocumentListener listenerPassword = new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) { validarContrasenasEnTiempoReal(); }
        @Override
        public void removeUpdate(DocumentEvent e) { validarContrasenasEnTiempoReal(); }
        @Override
        public void changedUpdate(DocumentEvent e) { validarContrasenasEnTiempoReal(); }
    };
    
    
    //metodo de prueba
    private void validarContrasenasEnTiempoReal() {
        String pass1 = new String(txtContra.getText());
        String pass2 = new String(txtConfirmarContra.getText());

        // Si ambos campos están vacíos, ocultamos o reseteamos el mensaje
        if (pass1.isEmpty() && pass2.isEmpty()) {
            lblMensajePassword.setText("");
            return;
        }

        // Comprobamos si coinciden
        if (pass1.equals(pass2)) {
            lblMensajePassword.setText("✓ Las contraseñas coinciden");
            lblMensajePassword.setForeground(new java.awt.Color(46, 125, 50)); // Verde oscuro
        } else {
            lblMensajePassword.setText("✗ Las contraseñas no coinciden");
            lblMensajePassword.setForeground(new java.awt.Color(198, 40, 40)); // Rojo
        }
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int idUsuario = Integer.parseInt(txtUsuario.getText());
        String username = txtNombreUsuario.getText();
        String password_hash = txtContra.getText();
        if (username.isEmpty() || password_hash.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, complete todos los campos.", 
                "Campos vacíos", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!password_hash.equals(txtConfirmarContra)) {
            JOptionPane.showMessageDialog(this, 
                "Las contraseñas no coinciden. Inténtelo de nuevo.", 
                "Error de coincidencia", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {

            ControladorLogin.actualizarUsuario(idUsuario, username, password_hash);

            JOptionPane.showMessageDialog(this, 
                "Usuario actualizado correctamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "El ID de usuario debe ser un número entero válido.", 
                "Si sale esto es porque se rompio el codigo y F", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtContra.setText(null);
        txtConfirmarContra.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensajePassword;
    private javax.swing.JTextField txtConfirmarContra;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
