/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Controler.ControladorConsulta;
import Model.CitaPendiente;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class FrmConsultas extends javax.swing.JFrame {

    ControladorConsulta controlador = new ControladorConsulta();
    private DefaultTableModel modelo;
    
    public FrmConsultas() {
        initComponents();
        IniciarModeloTabla();
        DiseñoTabla1();
        TamañoTabla();
        List<CitaPendiente> todosMedicamentos = controlador.listarCitasParaConsulta();
        cargarDatosTabla(todosMedicamentos);
    }

    private void IniciarModeloTabla(){
        modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        modelo.addColumn("idPaciente");
        modelo.addColumn("idMedico");
        modelo.addColumn("idCita");
        modelo.addColumn("nombre");       
        modelo.addColumn("numero_documento");
        TablaCitaPendiente.setModel(modelo);
    }
    private void TamañoTabla(){
        TableColumnModel columnModel = TablaCitaPendiente.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(10);
        columnModel.getColumn(2).setPreferredWidth(10);
        
    }
    private void DiseñoTabla1(){
        TablaCitaPendiente.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));

        // 2. Personalizamos el Renderizador del Header para forzar el color de fondo
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                headerLabel.setBackground(new Color(33, 150, 243)); // Azul Material
                headerLabel.setForeground(Color.WHITE);
                headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 15));
                headerLabel.setHorizontalAlignment(JLabel.CENTER);
                headerLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 1, new Color(25, 118, 210)));
                headerLabel.setOpaque(true);

                return headerLabel;
            }
        };

        // 3. Aplicamos el nuevo renderizador a todas las columnas
        for (int i = 0; i < TablaCitaPendiente.getColumnModel().getColumnCount(); i++) {
            TablaCitaPendiente.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    private void cargarDatosTabla(List<CitaPendiente> citaPendientes) {
        // 1. Limpiamos la tabla siempre al inicio
        modelo.setRowCount(0);
        
        // 2. Verificar si la lista que llegó está vacía o es nula
        if (citaPendientes == null || citaPendientes.isEmpty()) {
            System.out.println("No hay medicamentos para mostrar con los criterios actuales");
            return;
        }

        for (CitaPendiente h : citaPendientes) {
            modelo.addRow(new Object[]{
                h.getIdPaciente(),
                h.getIdMedico(), 
                h.getIdCita(), 
                h.getNombre(),
                h.getNumero_documento() 
            });
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaSintomas = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDiagnostico = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaTratamiento = new javax.swing.JTextArea();
        txtIdPaciente = new javax.swing.JTextField();
        txtIdMedico = new javax.swing.JTextField();
        txtIdCita = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCitaPendiente = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBuscarIdCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("N°Cita");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jTextField4.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, -1));

        txtAreaSintomas.setBackground(new java.awt.Color(204, 204, 204));
        txtAreaSintomas.setColumns(20);
        txtAreaSintomas.setRows(5);
        jScrollPane2.setViewportView(txtAreaSintomas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 90));

        txtAreaDiagnostico.setBackground(new java.awt.Color(204, 204, 204));
        txtAreaDiagnostico.setColumns(20);
        txtAreaDiagnostico.setRows(5);
        jScrollPane3.setViewportView(txtAreaDiagnostico);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 240, 90));

        txtAreaTratamiento.setBackground(new java.awt.Color(204, 204, 204));
        txtAreaTratamiento.setColumns(20);
        txtAreaTratamiento.setRows(5);
        jScrollPane4.setViewportView(txtAreaTratamiento);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, 90));

        txtIdPaciente.setEditable(false);
        txtIdPaciente.setBackground(new java.awt.Color(204, 204, 204));
        txtIdPaciente.setFocusable(false);
        getContentPane().add(txtIdPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 210, -1));

        txtIdMedico.setEditable(false);
        txtIdMedico.setBackground(new java.awt.Color(204, 204, 204));
        txtIdMedico.setFocusable(false);
        getContentPane().add(txtIdMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 210, -1));

        txtIdCita.setEditable(false);
        txtIdCita.setBackground(new java.awt.Color(204, 204, 204));
        txtIdCita.setFocusable(false);
        getContentPane().add(txtIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 210, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setFocusable(false);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 210, -1));

        txtDocumento.setEditable(false);
        txtDocumento.setBackground(new java.awt.Color(204, 204, 204));
        txtDocumento.setFocusable(false);
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 210, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sintomas");
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel2.setText("Diagnostico");
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Tratamiento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, 30));

        btnActualizar.setText("Actualizar");
        btnActualizar.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 100, 30));

        btnSalir.setText("Salir");
        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 90, 30));

        TablaCitaPendiente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaCitaPendiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCitaPendienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCitaPendiente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, 190));

        jLabel8.setText("Nombre Paciente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel5.setText("N° Medico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel4.setText("N° Paciente");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel7.setText("N° Cita");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel9.setText("N° Documento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        btnBuscarIdCita.setText("Buscar Cita");
        btnBuscarIdCita.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btnBuscarIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaCitaPendienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCitaPendienteMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) { //cantidad de click
            int fila = TablaCitaPendiente.getSelectedRow();

            if (fila != -1) {//no importa ponerlos en string ya q igual lo convertimos en guardar o actualizar
                // Obtener datos de la tabla
                String IdPaciente = TablaCitaPendiente.getValueAt(fila, 0).toString();
                String IdMedico = TablaCitaPendiente.getValueAt(fila, 1).toString();
                String IdCita = TablaCitaPendiente.getValueAt(fila, 2).toString();
                String Nombre = TablaCitaPendiente.getValueAt(fila, 3).toString();               
                String Documento = TablaCitaPendiente.getValueAt(fila, 4).toString();

                // Colocar en los TextBox (JTextField)
                txtIdPaciente.setText(IdPaciente);
                txtIdMedico.setText(IdMedico);
                txtIdCita.setText(IdCita);
                txtNombre.setText(Nombre);
                txtDocumento.setText(Documento);
            }
        }
    }//GEN-LAST:event_TablaCitaPendienteMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int IdPaciente = Integer.parseInt(txtIdPaciente.getText());
        int IdMedico = Integer.parseInt(txtIdMedico.getText());
        int IdCita = Integer.parseInt(txtIdCita.getText());
        String Sintomas = txtAreaSintomas.getText();
        String Diagnostico = txtAreaDiagnostico.getText();
        String Tratamiento = txtAreaTratamiento.getText();
        
        boolean resultado = controlador.CrearConsulta(IdPaciente, IdMedico, IdCita, Sintomas, Diagnostico, Tratamiento);
            
        if (resultado) {
            JOptionPane.showMessageDialog(
                this,
                "Medicamento realizado exitosamente: ",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar la cita",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCitaPendiente;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarIdCita;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextArea txtAreaDiagnostico;
    private javax.swing.JTextArea txtAreaSintomas;
    private javax.swing.JTextArea txtAreaTratamiento;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtIdCita;
    private javax.swing.JTextField txtIdMedico;
    private javax.swing.JTextField txtIdPaciente;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
