package Formularios;

import Controler.ControladorMedicamento;
import Excel.ExcelMedicamentoReader;
import Model.Medicamento;
import Model.MedicamentoDAO;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class FrmCargarMedicamento extends javax.swing.JFrame {
    private File archivoExcelSeleccionado;
    /**
     * Creates new form FrmCargarMedicamento
     */
    public FrmCargarMedicamento() {
        initComponents();
        FileChooserExcel.setFileFilter(new FileNameExtensionFilter("Archivos de Excel (*.xlsx, *.xls)", "xlsx", "xls"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooserExcel = new javax.swing.JFileChooser();
        txtRuta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FileChooserExcel.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        FileChooserExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserExcelActionPerformed(evt);
            }
        });
        getContentPane().add(FileChooserExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 781, 390));

        txtRuta.setEditable(false);
        txtRuta.setFocusable(false);
        getContentPane().add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 490, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("ARCHIVO EXCEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, -1));

        btnGuardar.setText("IMPORTAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FileChooserExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserExcelActionPerformed
           
        archivoExcelSeleccionado = FileChooserExcel.getSelectedFile();
    
        // 2. Verificamos que el usuario sí haya seleccionado un archivo
        if (archivoExcelSeleccionado != null) {

            // Ponemos la ruta en tu caja de texto
            txtRuta.setText(archivoExcelSeleccionado.getAbsolutePath());

            // Habilitamos tu botón principal de guardar
            btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_FileChooserExcelActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        java.net.URL location = org.apache.commons.io.input.BoundedInputStream.class.getProtectionDomain().getCodeSource().getLocation();
        System.out.println(">>> EL ARCHIVO JAR VIEJO ESTÁ AQUÍ: " + location.getFile());
        if (archivoExcelSeleccionado == null) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, selecciona primero un archivo de Excel.", 
                "Atención", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. Mostrar ventana de confirmación
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Deseas procesar el archivo seleccionado?\n" + archivoExcelSeleccionado.getName(),
            "Confirmar acción",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        // 2. Si presiona "Sí", ejecutas tu código
        if (confirmacion == JOptionPane.YES_OPTION) {
            List<Medicamento> lista = ExcelMedicamentoReader.leerMedicamentosDesdeExcel(archivoExcelSeleccionado);

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El archivo Excel está vacío o no contiene códigos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            MedicamentoDAO dao = new MedicamentoDAO();
        
            boolean OK = dao.guardarExcelMedicamento(lista);

            if (OK) {
                JOptionPane.showMessageDialog(this, "¡Proceso finalizado con éxito! Se procesaron " + lista.size() + " registros.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al ejecutar el procedimiento en la base de datos.", "Error BD", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCargarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCargarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCargarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCargarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCargarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooserExcel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
