package Formularios;

import Controler.ControladorReceta;
import Model.Receta;
import PDF.BotonDetalleRecetaRender;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class FrmHistorialReceta extends javax.swing.JFrame {

    ControladorReceta controladorReceta = new ControladorReceta();
    private DefaultTableModel modelo;
    public FrmHistorialReceta() {
        initComponents();
        IniciarModeloTabla();
        List<Receta> todasRecetas = controladorReceta.listarReceta(null, null, null, null);
        cargarDatosTabla(todasRecetas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaReceta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaReceta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void IniciarModeloTabla(){
        modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
                return column == 4; 
            }
        };        
        
        modelo.addColumn("id_receta");
        modelo.addColumn("id_consulta");
        modelo.addColumn("codigo_receta");
        modelo.addColumn("fecha_emision");
        modelo.addColumn("Ver Detalle");
        TablaReceta.setModel(modelo);
        
        BotonDetalleRecetaRender botonDetalle = new BotonDetalleRecetaRender(TablaReceta,0);
        TablaReceta.getColumnModel().getColumn(4).setCellRenderer(botonDetalle);
        TablaReceta.getColumnModel().getColumn(4).setCellEditor(botonDetalle);
        
        
    }
    private void cargarDatosTabla(List<Receta> receta) {
        // 1. Limpiamos la tabla siempre al inicio
        modelo.setRowCount(0);
        
        // 2. Verificar si la lista que llegó está vacía o es nula
        if (receta == null || receta.isEmpty()) {
            System.out.println("No hay receta para mostrar con los criterios actuales");
            return;
        }

        for (Receta h : receta) {
            modelo.addRow(new Object[]{
                h.getIdReceta(),
                h.getIdConsulta(), 
                h.getCodigoReceta(), 
                h.getFechaEmision()
            });
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorialReceta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaReceta;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
