/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import PDF.BotonDetalleRender;
import Model.CitaPendiente;
import Model.ConsultaHistorial;
import Model.ConsultaHistorialDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Lenovo
 */
public class FrmHistorialMedico extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    ConsultaHistorialDAO controlador = new ConsultaHistorialDAO(); 
    
    public FrmHistorialMedico() {
        initComponents();
        IniciarModeloTabla();
        
        List<ConsultaHistorial> todasCitas = controlador.listar();
        cargarDatosTabla(todasCitas);
    }
    
    private void IniciarModeloTabla(){
        modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 8; 
            }
        };
        modelo.addColumn("id_consulta");
        modelo.addColumn("id_cita");
        modelo.addColumn("id_paciente");
        modelo.addColumn("id_medico");
        modelo.addColumn("sintomas");       
        modelo.addColumn("diagnostico");
        modelo.addColumn("tratamiento_indicaciones");
        modelo.addColumn("fecha_consulta");
        modelo.addColumn("Acciones");
        TablaHistorialConsulta.setModel(modelo);
        
        BotonDetalleRender botonDetalle = new BotonDetalleRender(TablaHistorialConsulta,1);
        TablaHistorialConsulta.getColumnModel().getColumn(8).setCellRenderer(botonDetalle);
        TablaHistorialConsulta.getColumnModel().getColumn(8).setCellEditor(botonDetalle);
        
        TamañoTabla();
    }
    
    private void TamañoTabla(){
        TableColumnModel columnModel = TablaHistorialConsulta.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(1).setPreferredWidth(10);
        columnModel.getColumn(2).setPreferredWidth(10);
        columnModel.getColumn(3).setPreferredWidth(10);
        
    }
    
    private void cargarDatosTabla(List<ConsultaHistorial> listarConsultaHistorial) {
        // 1. Limpiamos la tabla siempre al inicio
        modelo.setRowCount(0);

        // 2. Verificar si la lista que llegó está vacía o es nula
        if (listarConsultaHistorial == null || listarConsultaHistorial.isEmpty()) {
            System.out.println("No hay medicamentos para mostrar con los criterios actuales");
            return;
        }

        for (ConsultaHistorial ch : listarConsultaHistorial) {
            Object[] fila = new Object[9]; // 6 columnas en total

            // Extraemos los datos respetando el orden de tus columnas:
            fila[0] = ch.getIdConsulta();
            fila[1] = ch.getIdCita();
            fila[2] = ch.getIdPaciente();
            fila[3] = ch.getIdMedico();
            fila[4] = ch.getSintomas();
            fila[5] = ch.getDiagnostico();
            fila[6] = ch.getTratamientoIndicaciones();
            fila[7] = ch.getFechaConsulta();

            // ¡Importante! Para la columna 5, pasamos un texto o el objeto cita.
            // Tu renderizador 'BotonPdfEditorRender' usará este valor o simplemente pintará el botón encima.
            fila[8] = "Ver Detalle"; 

            // 3. Agregamos la fila al modelo de la tabla
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHistorialConsulta = new javax.swing.JTable();
        txtIdCita = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaHistorialConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaHistorialConsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 130, 750, -1));
        getContentPane().add(txtIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, -1));

        jLabel1.setText("ID CITA");
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, 20));
        getContentPane().add(dateTimePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel3.setText("Fecha Consulta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorialMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorialMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaHistorialConsulta;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdCita;
    // End of variables declaration//GEN-END:variables
}
