/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Controler.ControladorHorario;
import Controler.ControladorMedico;
import Model.Horario;
import Model.Medico;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harold
 */
public class FrmHorario extends javax.swing.JFrame {
    
    ControladorHorario controlador = new ControladorHorario();
    ControladorMedico controladorMedico = new ControladorMedico();
    
    private DefaultTableModel modelo;
    public FrmHorario() {
        initComponents();
        IniciarModeloTabla();
        DiseñoTabla();
        CargarDatosTabla();
    }
    
    private void DiseñoTabla(){
        TablaHorarios.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));

        // 2. Personalizamos el Renderizador del Header para forzar el color de fondo
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                headerLabel.setBackground(new Color(33, 150, 243)); // Azul Material
                headerLabel.setForeground(Color.WHITE);
                headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 15));
                headerLabel.setHorizontalAlignment(JLabel.CENTER);
                headerLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 1, new Color(25, 118, 210)));
                headerLabel.setOpaque(true);

                return headerLabel;
            }
        };

        // 3. Aplicamos el nuevo renderizador a todas las columnas
        for (int i = 0; i < TablaHorarios.getColumnModel().getColumnCount(); i++) {
            TablaHorarios.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
    private void IniciarModeloTabla(){
        modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        modelo.addColumn("ID");
        modelo.addColumn("IDMEDICO");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        
        modelo.addColumn("dia_semana");
        modelo.addColumn("hora_inicio");
        modelo.addColumn("hora_fin");
        TablaHorarios.setModel(modelo);
    }
    
    private void CargarDatosTabla(){
        modelo.setRowCount(0);
        List<Horario> horario = controlador.listarHorarios();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        // Verificar si hay datos
        if (horario == null || horario.isEmpty()) {
            System.out.println("No hay horarios para mostrar");
            return;
        }
        modelo.setRowCount(0);
        
        //BUCLE PARA COLOCAR LOS DATOS EN EL ORDEN Q QUEREMOS
        for (Horario h : horario){
            Medico medico = h.getMedico();
            if (medico == null) {
                // Agregar datos con valores por defecto
                modelo.addRow(new Object[]{
                    h.getId_horario(),
                    "Sin médico",
                    "Sin médico",
                    "Sin médico",
                    h.getDia_semana(),
                    h.getHora_inicio().format(formatter),
                    h.getHora_fin().format(formatter)
                });
            } else {
                modelo.addRow(new Object[]{
                    h.getId_horario(),
                    medico.getId_medico(),
                    medico.getNombre(),
                    medico.getApellido(),
                    h.getDia_semana(),
                    h.getHora_inicio().format(formatter),
                    h.getHora_fin().format(formatter)
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHorarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblBuscarApellido = new javax.swing.JLabel();
        txtIdHorario = new javax.swing.JTextField();
        txtIdMedico = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoMedico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDiaSemana = new javax.swing.JTextField();
        txtDiaInicio = new javax.swing.JTextField();
        txtDiaFin = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        fecha = new com.github.lgooddatepicker.components.DateTimePicker();
        btntest = new javax.swing.JButton();
        txtTest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dpFecha = new com.github.lgooddatepicker.components.DatePicker();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tpInicio = new com.github.lgooddatepicker.components.TimePicker();
        jLabel10 = new javax.swing.JLabel();
        tpFin = new com.github.lgooddatepicker.components.TimePicker();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaHorariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaHorarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 690, 257));

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblBuscarApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar 16x16.png"))); // NOI18N
        lblBuscarApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuscarApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarApellidoMouseClicked(evt);
            }
        });
        jPanel1.add(lblBuscarApellido, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 30, 30));

        txtIdHorario.setEditable(false);
        txtIdHorario.setBackground(new java.awt.Color(204, 204, 204));
        txtIdHorario.setFocusable(false);
        getContentPane().add(txtIdHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, -1));

        txtIdMedico.setEditable(false);
        txtIdMedico.setBackground(new java.awt.Color(204, 204, 204));
        txtIdMedico.setFocusable(false);
        getContentPane().add(txtIdMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 90, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 120, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel2.setText("Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));
        getContentPane().add(txtApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, -1));

        jLabel12.setText("Apellido");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtDiaSemana.setText("jTextField1");
        getContentPane().add(txtDiaSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        txtDiaInicio.setEditable(false);
        txtDiaInicio.setFocusable(false);
        getContentPane().add(txtDiaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 130, -1));

        txtDiaFin.setEditable(false);
        txtDiaFin.setFocusable(false);
        getContentPane().add(txtDiaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 130, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.setBackground(new java.awt.Color(102, 255, 102));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        btnActualizar.setText("Registrar");
        btnActualizar.setBackground(new java.awt.Color(0, 204, 0));
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 120, 40));

        btnEliminar.setText("Eliminar");
        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 120, 40));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        btntest.setText("jButton1");
        btntest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntestActionPerformed(evt);
            }
        });
        getContentPane().add(btntest, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        txtTest.setText("jTextField1");
        getContentPane().add(txtTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 140, -1));

        jLabel3.setText("Dia de la semana");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel4.setText("Horario Inicio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel5.setText("idHorario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel6.setText("idMedico");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel7.setText("Horario Fin");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, 20));
        getContentPane().add(dpFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 210, -1));

        jLabel8.setText("Fecha");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 60, -1));

        jLabel9.setText("Inicio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));
        getContentPane().add(tpInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel10.setText("Fin");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));
        getContentPane().add(tpFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.setBackground(new java.awt.Color(0, 204, 51));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 100, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Medico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea1.setFocusable(false);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 290, 180));

        jLabel11.setText("FORMULARIO HORARIO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Seleccionar Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea2.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 290, 170));

        btnLimpiar.setBackground(new java.awt.Color(0, 153, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaHorariosMouseClicked
        if (evt.getClickCount() == 2) { //cantidad de click
            int fila = TablaHorarios.getSelectedRow();

            if (fila != -1) {
                // Obtener datos de la tabla
                String idHorario = TablaHorarios.getValueAt(fila, 0).toString();
                String idMedico = TablaHorarios.getValueAt(fila, 1).toString();
                String nombre = TablaHorarios.getValueAt(fila, 2).toString();
                String apellido = TablaHorarios.getValueAt(fila, 3).toString();
                
                String diaSemana = TablaHorarios.getValueAt(fila, 4).toString();
                String horaInicio = TablaHorarios.getValueAt(fila, 5).toString();
                String horaFin = TablaHorarios.getValueAt(fila, 6).toString();

                // Colocar en los TextBox (JTextField)
                txtIdHorario.setText(idHorario);
                txtIdMedico.setText(idMedico);
                txtNombre.setText(nombre);
                txtApellido.setText(apellido);
                txtDiaSemana.setText(diaSemana);
                txtDiaInicio.setText(horaInicio);
                txtDiaFin.setText(horaFin);
            }
        }
    }//GEN-LAST:event_TablaHorariosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        modelo.setRowCount(0);
        List<Horario> horario = controlador.listarHorariosBusqueda(txtApellido.getText());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        // Verificar si hay datos
        if (horario == null || horario.isEmpty()) {
            System.out.println("No hay horarios para mostrar");
            return;
        }
        modelo.setRowCount(0);
        
        //BUCLE PARA COLOCAR LOS DATOS EN EL ORDEN Q QUEREMOS
        for (Horario h : horario){
            Medico medico = h.getMedico();
            if (medico == null) {
                // Agregar datos con valores por defecto
                modelo.addRow(new Object[]{
                    h.getId_horario(),
                    "Sin médico",
                    "Sin médico",
                    "Sin médico",
                    h.getDia_semana(),
                    h.getHora_inicio().format(formatter),
                    h.getHora_fin().format(formatter)
                });
            } else {
                modelo.addRow(new Object[]{
                    h.getId_horario(),
                    medico.getId_medico(),
                    medico.getNombre(),
                    medico.getApellido(),
                    h.getDia_semana(),
                    h.getHora_inicio().format(formatter),
                    h.getHora_fin().format(formatter)
                });
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int idMedico = Integer.parseInt(txtIdMedico.getText().trim());
        int diaSemana = Integer.parseInt(txtDiaSemana.getText());
        String Apellido = txtApellido.getText();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDateTime horaInicio = LocalDateTime.parse(txtDiaInicio.getText(),formatter);
        LocalDateTime horaFin = LocalDateTime.parse(txtDiaFin.getText(),formatter);

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Generar horarios del médico ID: " + idMedico +" ,Apellido"+ "?",
            "Confirmar actualización",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            boolean resultado = controlador.ActualizarHorario(idMedico, diaSemana, horaInicio, horaFin);

            if (resultado) {
                JOptionPane.showMessageDialog(
                    this,
                    "Horario generar exitosamente para el médico ID: " + idMedico,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se pudo generar el horario. Verifica que el médico exista.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
        CargarDatosTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int idHorario = Integer.parseInt(txtIdHorario.getText());
        controlador.EliminarHorario(idHorario);
        CargarDatosTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btntestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntestActionPerformed
        // TODO add your handling code here:
        //recordar borrar es solo para test ni se os ocurra hacer algo aparte de test solo testt
        LocalDateTime fechaHoraSeleccionada = fecha.getDateTimePermissive();
        DateTimeFormatter formato24h = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String texto24h = fechaHoraSeleccionada.format(formato24h);
        
        txtTest.setText(texto24h);
    }//GEN-LAST:event_btntestActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formato24h = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        LocalDate fechaSeleccionada = dpFecha.getDate();
        LocalTime horaInicio = tpInicio.getTime();
        LocalTime horaFin = tpFin.getTime();
        
        LocalDateTime fechaHoraInicio = LocalDateTime.of(fechaSeleccionada, horaInicio);
        LocalDateTime fechaHoraFin = LocalDateTime.of(fechaSeleccionada, horaFin);
        
        String textoFechaHoraInicio = fechaHoraInicio.format(formato24h);
        String textoFechaHoraFin = fechaHoraFin.format(formato24h);
        
        txtDiaInicio.setText(textoFechaHoraInicio);
        txtDiaFin.setText(textoFechaHoraFin);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void lblBuscarApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarApellidoMouseClicked
        // TODO add your handling code here:
        String apellidoMedico = txtApellidoMedico.getText();
        List<Medico> listaMedicoApellido = controladorMedico.listarMedicoApellido(apellidoMedico);
        
        int idMedico = listaMedicoApellido.get(0).getId_medico();
        String nombreMedico= listaMedicoApellido.get(0).getNombre();
        String apellido= listaMedicoApellido.get(0).getApellido();
        
        txtIdMedico.setText(idMedico+"");
        txtNombre.setText(nombreMedico);
        txtApellidoMedico.setText(apellido);
        
    }//GEN-LAST:event_lblBuscarApellidoMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaHorarios;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btntest;
    private com.github.lgooddatepicker.components.DatePicker dpFecha;
    private com.github.lgooddatepicker.components.DateTimePicker fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblBuscarApellido;
    private com.github.lgooddatepicker.components.TimePicker tpFin;
    private com.github.lgooddatepicker.components.TimePicker tpInicio;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoMedico;
    private javax.swing.JTextField txtDiaFin;
    private javax.swing.JTextField txtDiaInicio;
    private javax.swing.JTextField txtDiaSemana;
    private javax.swing.JTextField txtIdHorario;
    private javax.swing.JTextField txtIdMedico;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTest;
    // End of variables declaration//GEN-END:variables
}
