/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Model.SesionUsuario;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        Estilos.TemaManager.inicializarTema();
        initComponents();
        setLocationRelativeTo(null);

        btnCambiarTema.setText("🌙 Modo Oscuro");
        
        Model.Usuario usuarioLogueado = Model.SesionUsuario.getInstancia().getUsuarioLogueado();
        
        if (usuarioLogueado != null) {      
        // 3. Extraemos los datos que guardó el DAO
            String nombre = usuarioLogueado.getUsername();
            int rol = usuarioLogueado.getId_rol();
            String nombreRol = usuarioLogueado.getNombre_rol();
            PermisoRol(nombreRol);        
            lblNombre.setText(nombre);
            lblNombreUsuario.setText(nombreRol);
            
        }           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblimg = new javax.swing.JLabel();
        btnCambiarTema = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuRegistrarCita = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuTriaje = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuHistorialCita = new javax.swing.JMenuItem();
        MenuHistorialMedico = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        MenuRegistrarConsulta = new javax.swing.JMenuItem();
        MenuPrincipalReceta = new javax.swing.JMenu();
        MenuVerRecetas = new javax.swing.JMenuItem();
        MenuReceta = new javax.swing.JMenuItem();
        MenuMedicamento = new javax.swing.JMenu();
        MenuRegistrarMedicamento = new javax.swing.JMenuItem();
        MenuExcel = new javax.swing.JMenuItem();
        MenuContraseña = new javax.swing.JMenu();
        MenuHorarioMedico = new javax.swing.JMenuItem();
        MenuPerfil = new javax.swing.JMenuItem();
        MenuCambiarContraseña = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btnCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 70, 20));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 150, 20));

        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VidaSalud.png"))); // NOI18N
        jPanel1.add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        btnCambiarTema.setText("Tema");
        btnCambiarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarTemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        jMenu1.setText("Citas");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        MenuRegistrarCita.setText("Registrar Cita");
        MenuRegistrarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarCitaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuRegistrarCita);

        jMenuItem2.setText("Ver Mis Citas");
        jMenu1.add(jMenuItem2);

        MenuTriaje.setText("Triaje");
        MenuTriaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTriajeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuTriaje);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Historial Medico");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        MenuHistorialCita.setText("Ver Historial Cita");
        MenuHistorialCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHistorialCitaActionPerformed(evt);
            }
        });
        jMenu2.add(MenuHistorialCita);

        MenuHistorialMedico.setText("Ver Historial Medico");
        MenuHistorialMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHistorialMedicoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuHistorialMedico);

        jMenuBar1.add(jMenu2);

        MenuConsulta.setText("Consulta");

        MenuRegistrarConsulta.setText("RegistrarConsulta");
        MenuRegistrarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarConsultaActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuRegistrarConsulta);

        jMenuBar1.add(MenuConsulta);

        MenuPrincipalReceta.setText("Recetas");
        MenuPrincipalReceta.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        MenuVerRecetas.setText("Ver Recetas");
        MenuVerRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVerRecetasActionPerformed(evt);
            }
        });
        MenuPrincipalReceta.add(MenuVerRecetas);

        MenuReceta.setText("Generar Receta");
        MenuReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRecetaActionPerformed(evt);
            }
        });
        MenuPrincipalReceta.add(MenuReceta);

        jMenuBar1.add(MenuPrincipalReceta);

        MenuMedicamento.setText("Medicamentos");

        MenuRegistrarMedicamento.setText("Registar Medicamento");
        MenuRegistrarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRegistrarMedicamentoActionPerformed(evt);
            }
        });
        MenuMedicamento.add(MenuRegistrarMedicamento);

        MenuExcel.setText("Cargar Excel Medicamento");
        MenuExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExcelActionPerformed(evt);
            }
        });
        MenuMedicamento.add(MenuExcel);

        jMenuBar1.add(MenuMedicamento);

        MenuContraseña.setText("Mi Cuenta");
        MenuContraseña.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        MenuHorarioMedico.setText("Horario Medico");
        MenuHorarioMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHorarioMedicoActionPerformed(evt);
            }
        });
        MenuContraseña.add(MenuHorarioMedico);

        MenuPerfil.setText("Crear Perfil");
        MenuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPerfilActionPerformed(evt);
            }
        });
        MenuContraseña.add(MenuPerfil);

        MenuCambiarContraseña.setText("Cambiar Contraseña");
        MenuCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCambiarContraseñaActionPerformed(evt);
            }
        });
        MenuContraseña.add(MenuCambiarContraseña);

        jMenuBar1.add(MenuContraseña);

        jMenu5.setText("Sesión");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        btnCerrar.setText("Cerrar");
        jMenu5.add(btnCerrar);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void abrirFormulario(JFrame formulario) {
        this.setEnabled(false);
        
        //Carga preferencia de TEMA OSCURO / CLARO
        SwingUtilities.updateComponentTreeUI(formulario);
        
        formulario.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        formulario.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                setEnabled(true);
                toFront();
                requestFocus();
            }
        });

        formulario.setLocationRelativeTo(this);
        formulario.setVisible(true);
    }
    
    private void MenuRegistrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarCitaActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmSolicitar_citas());
    }//GEN-LAST:event_MenuRegistrarCitaActionPerformed

    private void MenuHistorialCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHistorialCitaActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmHistorial_Paciente());
    }//GEN-LAST:event_MenuHistorialCitaActionPerformed

    private void MenuRegistrarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarMedicamentoActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmMedicamento());
    }//GEN-LAST:event_MenuRegistrarMedicamentoActionPerformed

    private void MenuHorarioMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHorarioMedicoActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmHorario());
    }//GEN-LAST:event_MenuHorarioMedicoActionPerformed

    private void MenuTriajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTriajeActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmTriaje());
    }//GEN-LAST:event_MenuTriajeActionPerformed

    private void MenuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPerfilActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmPerfil());
    }//GEN-LAST:event_MenuPerfilActionPerformed

    private void MenuRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRecetaActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmGenerarRecetas());
    }//GEN-LAST:event_MenuRecetaActionPerformed

    private void MenuRegistrarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRegistrarConsultaActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmConsultas());
    }//GEN-LAST:event_MenuRegistrarConsultaActionPerformed
    
    private void PermisoRol(String nombreRol){
            // Si el usuario es un "Paciente", le ocultamos el botón de configuraciones del sistema
            if (nombreRol.equalsIgnoreCase("Enfermero")) {
                MenuConsulta.setVisible(false);
                MenuPrincipalReceta.setVisible(false);
                MenuMedicamento.setVisible(false);
                MenuHorarioMedico.setVisible(false);
                MenuPerfil.setVisible(false);
                MenuHistorialMedico.setVisible(false);
            }else if(nombreRol.equalsIgnoreCase("Medico")){
                MenuRegistrarCita.setVisible(false);
                MenuTriaje.setVisible(false);
                MenuHorarioMedico.setVisible(false);
                MenuPerfil.setVisible(false);
            }
    }
    private void actualizarTextoBotonTema() {
        if (Estilos.TemaManager.esOscuro()) {
            btnCambiarTema.setText("☀️ Modo Claro");
        } else {
            btnCambiarTema.setText("🌙 Modo Oscuro");
        }
    }
    
    private void btnCambiarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarTemaActionPerformed
        // TODO add your handling code here:
        boolean tema = true;
        Estilos.TemaManager.alternarTema(this);

        // 2. Actualizamos el texto del botón según el nuevo estado
        actualizarTextoBotonTema();
//        // (Opcional) Cambiar el texto del botón según el modo
//        if (Estilos.TemaManager.esOscuro()) {
//            btnCambiarTema.setText("☀️ Modo Claro");   
//            Estilos.TemaManager.alternarTema(this);
//        } else {
//            btnCambiarTema.setText("🌙 Modo Oscuro");
//            Estilos.TemaManager.alternarTema(this);
//        }
    }//GEN-LAST:event_btnCambiarTemaActionPerformed

    private void MenuVerRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVerRecetasActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmRecetas_Paciente());
    }//GEN-LAST:event_MenuVerRecetasActionPerformed

    private void MenuHistorialMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHistorialMedicoActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmHistorialMedico());
    }//GEN-LAST:event_MenuHistorialMedicoActionPerformed

    private void MenuCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCambiarContraseñaActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmContraseña());
    }//GEN-LAST:event_MenuCambiarContraseñaActionPerformed

    private void MenuExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExcelActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FrmCargarMedicamento());
    }//GEN-LAST:event_MenuExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Estilos.TemaManager.inicializarTema();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCambiarContraseña;
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenu MenuContraseña;
    private javax.swing.JMenuItem MenuExcel;
    private javax.swing.JMenuItem MenuHistorialCita;
    private javax.swing.JMenuItem MenuHistorialMedico;
    private javax.swing.JMenuItem MenuHorarioMedico;
    private javax.swing.JMenu MenuMedicamento;
    private javax.swing.JMenuItem MenuPerfil;
    private javax.swing.JMenu MenuPrincipalReceta;
    private javax.swing.JMenuItem MenuReceta;
    private javax.swing.JMenuItem MenuRegistrarCita;
    private javax.swing.JMenuItem MenuRegistrarConsulta;
    private javax.swing.JMenuItem MenuRegistrarMedicamento;
    private javax.swing.JMenuItem MenuTriaje;
    private javax.swing.JMenuItem MenuVerRecetas;
    private javax.swing.JButton btnCambiarTema;
    private javax.swing.JMenuItem btnCerrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblimg;
    // End of variables declaration//GEN-END:variables
}
