package Formularios;

import Controler.ControladorMedicamento;
import Model.Medicamento;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


public class FrmMedicamento extends javax.swing.JFrame {

    ControladorMedicamento controlador = new ControladorMedicamento();
    private DefaultTableModel modelo;
    
    public FrmMedicamento() {
        initComponents();
        IniciarModeloTabla();
        DiseñoTabla();
        TamañoTabla();
        List<Medicamento> todosMedicamentos = controlador.listarMedicamentos();
        cargarDatosTabla(todosMedicamentos);
    }
    
    private void IniciarModeloTabla(){
        modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        modelo.addColumn("IdMedicamento");
        modelo.addColumn("Nombre Comercial");
        modelo.addColumn("Nombre Generico");
        modelo.addColumn("Presentacion");       
        modelo.addColumn("Stock");
        modelo.addColumn("Precio Venta");
        modelo.addColumn("codigo medicamento");
        TablaMedicamento.setModel(modelo);
    }
    private void TamañoTabla(){
        TableColumnModel columnModel = TablaMedicamento.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(10);
        columnModel.getColumn(4).setPreferredWidth(10);
        columnModel.getColumn(5).setPreferredWidth(10);
    }
    private void DiseñoTabla(){
        TablaMedicamento.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));

        // 2. Personalizamos el Renderizador del Header para forzar el color de fondo
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                headerLabel.setBackground(new Color(33, 150, 243)); // Azul Material
                headerLabel.setForeground(Color.WHITE);
                headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 15));
                headerLabel.setHorizontalAlignment(JLabel.CENTER);
                headerLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 1, new Color(25, 118, 210)));
                headerLabel.setOpaque(true);

                return headerLabel;
            }
        };

        // 3. Aplicamos el nuevo renderizador a todas las columnas
        for (int i = 0; i < TablaMedicamento.getColumnModel().getColumnCount(); i++) {
            TablaMedicamento.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
    private void cargarDatosTabla(List<Medicamento> medicamentos) {
        // 1. Limpiamos la tabla siempre al inicio
        modelo.setRowCount(0);
        
        // 2. Verificar si la lista que llegó está vacía o es nula
        if (medicamentos == null || medicamentos.isEmpty()) {
            System.out.println("No hay medicamentos para mostrar con los criterios actuales");
            return;
        }

        for (Medicamento h : medicamentos) {
            modelo.addRow(new Object[]{
                h.getId_medicamento(),
                h.getNombre_comercial(), 
                h.getNombre_generico(), 
                h.getPresentacion(),
                h.getStock(), 
                h.getPrecio_venta(),
                h.getCodigo_medicamento()
            });
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMedicamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre_comercial = new javax.swing.JTextField();
        txtNombre_generico = new javax.swing.JTextField();
        txtPresentacion = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio_venta = new javax.swing.JTextField();
        txtMedicamento = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMedicamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMedicamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 630, 270));

        jLabel1.setText("N°Medicamento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre Comercial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre Generico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Presentacion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Stock");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Precio Venta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));
        getContentPane().add(txtNombre_comercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, -1));
        getContentPane().add(txtNombre_generico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 130, -1));
        getContentPane().add(txtPresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, -1));
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 150, -1));
        getContentPane().add(txtPrecio_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 150, -1));

        txtMedicamento.setEditable(false);
        txtMedicamento.setFocusable(false);
        getContentPane().add(txtMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, -1));

        btnActualizar.setBackground(new java.awt.Color(51, 153, 255));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 110, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 110, 30));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("SALIR");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 463, 110, 30));

        btnAgregar.setBackground(new java.awt.Color(51, 255, 102));
        btnAgregar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregar.setText("AGREGAR NUEVO");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 160, 40));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setText("LIMPIAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 150, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("FORMULARIO MEDICAMENTO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 150, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("CODIGO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Medicamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea1.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 600, 180));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("MEDICAMENTOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre_comercial = txtNombre_comercial.getText();                      
            String nombre_generico= txtNombre_generico.getText();
            String presentacion= txtPresentacion.getText();
            int stock= Integer.parseInt(txtStock.getText());
            double precio_venta=Double.parseDouble(txtPrecio_venta.getText());
            String codigo_medicamento = txtCodigo.getText();
            
            boolean resultado = controlador.CrearMedicamento(nombre_comercial, nombre_generico, presentacion, stock,precio_venta,codigo_medicamento);
            
            if (resultado) {
                JOptionPane.showMessageDialog(
                    this,
                    "Medicamento realizado exitosamente: ",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar la cita",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (NullPointerException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "La fila seleccionada contiene celdas vacías.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int id_medicamento = Integer.parseInt(txtMedicamento.getText());
        String nombre_comercial = txtNombre_comercial.getText();                      
        String nombre_generico= txtNombre_generico.getText();
        String presentacion= txtPresentacion.getText();
        int stock= Integer.parseInt(txtStock.getText());
        double precio_venta=Double.parseDouble(txtPrecio_venta.getText());

        boolean resultado = controlador.ActualizarMedicamento(id_medicamento,nombre_comercial, nombre_generico, presentacion, stock,precio_venta);

        if (resultado) {
            JOptionPane.showMessageDialog(
                this,
                "Medicamento realizado exitosamente: ",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar la cita",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
        
        List<Medicamento> todosMedicamentos = controlador.listarMedicamentos();
        cargarDatosTabla(todosMedicamentos);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int id_medicamento = Integer.parseInt(txtMedicamento.getText());
        controlador.EliminarMedicamento(id_medicamento);
        
        List<Medicamento> todosMedicamentos = controlador.listarMedicamentos();
        cargarDatosTabla(todosMedicamentos);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TablaMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMedicamentoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) { //cantidad de click
            int fila = TablaMedicamento.getSelectedRow();

            if (fila != -1) {//no importa ponerlos en string ya q igual lo convertimos en guardar o actualizar
                // Obtener datos de la tabla
                String id_medicamento = TablaMedicamento.getValueAt(fila, 0).toString();
                String nombre_comercial = TablaMedicamento.getValueAt(fila, 1).toString();
                String nombre_generico = TablaMedicamento.getValueAt(fila, 2).toString();
                String presentacion = TablaMedicamento.getValueAt(fila, 3).toString();               
                String stock = TablaMedicamento.getValueAt(fila, 4).toString();
                String precio_venta = TablaMedicamento.getValueAt(fila, 5).toString();
                String codigo_medicamento = TablaMedicamento.getValueAt(fila, 6).toString();
                // Colocar en los TextBox (JTextField)
                txtMedicamento.setText(id_medicamento);
                txtNombre_comercial.setText(nombre_comercial);
                txtNombre_generico.setText(nombre_generico);
                txtPresentacion.setText(presentacion);
                txtStock.setText(stock);
                txtPrecio_venta.setText(precio_venta);
                txtCodigo.setText(codigo_medicamento);
                
                txtCodigo.setEditable(false);
            }
        }
    }//GEN-LAST:event_TablaMedicamentoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtMedicamento.setText(null);
        txtNombre_comercial.setText(null);
        txtNombre_generico.setText(null);
        txtPresentacion.setText(null);
        txtStock.setText(null);
        txtPrecio_venta.setText(null);
        txtCodigo.setText(null);
        
        txtCodigo.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        FlatLightLaf.setup();
        UIManager.put("Component.arc", 8);
        UIManager.put("TextComponent.arc", 10);
        UIManager.put("Table.showHorizontalLines", true);
        UIManager.put("Table.showVerticalLines", false);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMedicamento;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtNombre_comercial;
    private javax.swing.JTextField txtNombre_generico;
    private javax.swing.JTextField txtPrecio_venta;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
