package Formularios;

import Controler.ControladorReceta;
import Model.Receta;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FrmRecetas_Paciente extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    ControladorReceta controlador = new ControladorReceta(); 
    
    public FrmRecetas_Paciente() {
        initComponents();
        
        IniciarModeloTabla();
        DiseñoTabla();
        List<Receta> todasCitas = controlador.listarReceta(null, null, null, null);
        cargarDatosTabla(todasCitas);
    }
    
    private void IniciarModeloTabla(){
        modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        modelo.addColumn("id_receta");
        modelo.addColumn("id_consulta");
        modelo.addColumn("codigo_receta");
        modelo.addColumn("fecha_emision");       
        TablaReceta.setModel(modelo);
    }
    
    private void DiseñoTabla(){
        TablaReceta.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));

        // 2. Personalizamos el Renderizador del Header para forzar el color de fondo
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel headerLabel = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                headerLabel.setBackground(new Color(33, 150, 243)); // Azul Material
                headerLabel.setForeground(Color.WHITE);
                headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 15));
                headerLabel.setHorizontalAlignment(JLabel.CENTER);
                headerLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 1, new Color(25, 118, 210)));
                headerLabel.setOpaque(true);

                return headerLabel;
            }
        };

        // 3. Aplicamos el nuevo renderizador a todas las columnas
        for (int i = 0; i < TablaReceta.getColumnModel().getColumnCount(); i++) {
            TablaReceta.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
    private void cargarDatosTabla(List<Receta> listarReceta) {
        // 1. Limpiamos la tabla siempre al inicio
        modelo.setRowCount(0);

        // 2. Verificar si la lista que llegó está vacía o es nula
        if (listarReceta == null || listarReceta.isEmpty()) {
            System.out.println("No hay medicamentos para mostrar con los criterios actuales");
            return;
        }

        for (Receta receta : listarReceta) {
            Object[] fila = new Object[5]; // # columnas en total

            // Extraemos los datos respetando el orden de tus columnas:
            fila[0] = receta.getIdReceta();
            fila[1] = receta.getIdConsulta();
            fila[2] = receta.getCodigoReceta();
            fila[3] = receta.getFechaEmision();

            // ¡Importante! Para la columna 5, pasamos un texto o el objeto cita.
            // Tu renderizador 'BotonPdfEditorRender' usará este valor o simplemente pintará el botón encima.
            fila[4] = "Ver Detalle"; 

            // 3. Agregamos la fila al modelo de la tabla
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TablaReceta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaReceta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRecetas_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaReceta;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
