package Formularios;

import APIWhatsApp.TwilioService;
import Controler.ControladorCita;
import Controler.ControladorPaciente;
import Model.CitaDAO;
import Model.CitaNotificacion;
import Model.ListaHorarioCita;
import Model.Paciente;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FrmSolicitar_citas extends javax.swing.JFrame {

    ControladorPaciente controladorPaciente = new ControladorPaciente();
    ControladorCita controlador = new ControladorCita();
    private DefaultTableModel modelo;
    
    public FrmSolicitar_citas() {
        initComponents();
        txtFechaNacimiento.setSettings(Estilos.TemaManager.obtenerDatePickerSettings());
        dpFecha.setSettings(Estilos.TemaManager.obtenerDatePickerSettings());
      
        IniciarModeloTabla();
        
        List<ListaHorarioCita> todosLosHorariosMedicos = controlador.listarMedicoHorario();
        cargarDatosTabla(todosLosHorariosMedicos);
        //Model.Usuario usuarioLogueado = Model.SesionUsuario.getInstancia().getUsuarioLogueado();
        
        //if (usuarioLogueado != null) {      
        // 3. Extraemos los datos que guardó el DAO
            //String nombre = usuarioLogueado.getUsername();
            //int id_usuario = usuarioLogueado.getId_usuario();
            
            //lblid_usuario.setText(""+id_usuario);
            
            // 5. EJEMPLO DE CONTROL DE ACCESOS:
//            // Si el usuario es un "Paciente", le ocultamos el botón de configuraciones del sistema
//            if (rol.equalsIgnoreCase("Paciente")) {
//                btnConfiguracionSistema.setVisible(false); // Desaparece el botón
//                // btnReportes.setEnabled(false); // O lo dejas visible pero bloqueado (gris)
//            }
        //} 
    }
    
    private void IniciarModeloTabla(){
        modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        modelo.addColumn("IDMEDICO");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Especialidad");
        
        modelo.addColumn("dia_semana");
        modelo.addColumn("hora_inicio");
        modelo.addColumn("hora_fin");
        TablaHorarioCita.setModel(modelo);
    }
    
    private void cargarDatosTabla(List<ListaHorarioCita> listaHorarioCitas) {
        // 1. Limpiamos la tabla siempre al inicio
        modelo.setRowCount(0);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        // 2. Verificar si la lista que llegó está vacía o es nula
        if (listaHorarioCitas == null || listaHorarioCitas.isEmpty()) {
            System.out.println("No hay horarios para mostrar con los criterios actuales");
            return;
        }

        // 3. Tu mismo bucle (se mantiene intacto, solo cambia la variable a listaHorarios)
        for (ListaHorarioCita h : listaHorarioCitas) {
            modelo.addRow(new Object[]{
                h.getId_medico(),
                h.getNombre(), 
                h.getApellido(), 
                h.getEspecialidad(),
                h.getDia_semana(), 
                h.getHora_inicio().format(formatter), 
                h.getHora_fin().format(formatter)
            });
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDoc = new javax.swing.ButtonGroup();
        btnGroupGenero = new javax.swing.ButtonGroup();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtIdPaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMotivo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaHorarioCita = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtApellidoMedico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboEspecialidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarMedico = new javax.swing.JButton();
        btnRegistarCita = new javax.swing.JButton();
        btnLimpiarHorario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblid_usuario = new javax.swing.JLabel();
        txtFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        btnRegistrarPaciente = new javax.swing.JButton();
        btnActualizarPaciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellidoPaciente = new javax.swing.JTextField();
        rbDni = new javax.swing.JRadioButton();
        rbCE = new javax.swing.JRadioButton();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dpFecha = new com.github.lgooddatepicker.components.DatePicker();
        tpHora = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar por DNI");
        btnBuscar.setBorder(null);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 170, 40));

        jLabel11.setText("idPaciente");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtIdPaciente.setEditable(false);
        txtIdPaciente.setBackground(new java.awt.Color(204, 204, 204));
        txtIdPaciente.setFocusable(false);
        getContentPane().add(txtIdPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 60, -1));

        jLabel1.setText("Nombres");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(txtNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, -1));

        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        jLabel4.setText("Tipo Doc");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("DNI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, -1));

        jLabel14.setText("telefono");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, -1));

        jLabel13.setText("Genero");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel12.setText("Fecha Nacimiento");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtAreaMotivo.setColumns(20);
        txtAreaMotivo.setRows(5);
        txtAreaMotivo.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtAreaMotivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 310, 80));

        jLabel10.setText("Motivo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        TablaHorarioCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaHorarioCita);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 830, 230));

        jLabel7.setText("Medico");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        getContentPane().add(txtApellidoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 130, -1));

        jLabel6.setText("Especialidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        cboEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Medicina General", "Traumatologia", "Dermatologia", "Oncologia", "Oftamologia" }));
        getContentPane().add(cboEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 130, -1));

        jLabel9.setText("Hora");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        jLabel8.setText("Fecha");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        btnBuscarMedico.setText("BuscarMedico");
        btnBuscarMedico.setBackground(new java.awt.Color(51, 204, 255));
        btnBuscarMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 110, 30));

        btnRegistarCita.setText("Registar");
        btnRegistarCita.setBackground(new java.awt.Color(0, 204, 0));
        btnRegistarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistarCita.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarCitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 110, 30));

        btnLimpiarHorario.setText("Limpiar");
        btnLimpiarHorario.setBackground(new java.awt.Color(0, 204, 204));
        btnLimpiarHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarHorario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpiarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 110, 30));

        jButton3.setText("Salir");
        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 110, 30));
        getContentPane().add(lblid_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 130, 20));
        getContentPane().add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        btnRegistrarPaciente.setText("Registrar Paciente");
        btnRegistrarPaciente.setBackground(new java.awt.Color(0, 204, 0));
        btnRegistrarPaciente.setBorder(null);
        btnRegistrarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarPaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 170, 40));

        btnActualizarPaciente.setText("Actualizar Paciente");
        btnActualizarPaciente.setBackground(new java.awt.Color(0, 153, 255));
        btnActualizarPaciente.setBorder(null);
        btnActualizarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarPaciente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 170, 40));

        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel15.setText("Direccion");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 170, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 170, -1));
        getContentPane().add(txtApellidoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, -1));

        btnGroupDoc.add(rbDni);
        rbDni.setText("DNI");
        getContentPane().add(rbDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        btnGroupDoc.add(rbCE);
        rbCE.setText("C.E.");
        getContentPane().add(rbCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        btnGroupGenero.add(rbHombre);
        rbHombre.setText("Hombre");
        getContentPane().add(rbHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        btnGroupGenero.add(rbMujer);
        rbMujer.setText("Mujer");
        getContentPane().add(rbMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jButton1.setText("Limpiar Paciente");
        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 170, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea1.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 940, 300));
        getContentPane().add(dpFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));
        getContentPane().add(tpHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        List<Paciente> pacientes = controlador.listarHorariosBusqueda(txtDNI.getText());
        DateTimeFormatter formatoEspanol = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        if (pacientes != null && !pacientes.isEmpty()) {

            // 3. extraes el primer objeto Horario de la lista (índice 0)
            Paciente paciente = pacientes.get(0);

            // 4. Pasas los atributos del objeto a tus JTextField
            // (Asumiendo que tu clase Horario tiene los métodos get correspondientes)
            txtIdPaciente.setText(String.valueOf(paciente.getId_paciente())); 
            txtNombrePaciente.setText(paciente.getNombre());
            txtApellidoPaciente.setText(paciente.getApellido());
            
            String tipoDoc = paciente.getTipo_documento();
            if ("DNI".equals(tipoDoc)) {
                rbDni.setSelected(true); // DNI
            } else if ("C.E.".equals(tipoDoc)) {
                rbCE.setSelected(true);  // CE
            }
            //txtTipoDoc.setText(paciente.getTipo_documento());
            
            
            txtDNI.setText(paciente.getNumero_documento());
            txtFechaNacimiento.setText(paciente.getFecha_nacimiento().format(formatoEspanol));
            
            String tipoGenero = paciente.getGenero();
            if ("Hombre".equals(tipoGenero)) {
                rbHombre.setSelected(true); 
            } else if ("Mujer".equals(tipoGenero)) {
                rbMujer.setSelected(true);  
            }
            //txtGenero.setText(paciente.getGenero());
            
            txtTelefono.setText(paciente.getTelefono());            
            txtEmail.setText(paciente.getEmail());
            txtDireccion.setText(paciente.getDireccion());
            
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron Paciente para el DNI ingresado.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMedicoActionPerformed
        // TODO add your handling code here:
        String especialidad;
        String apellidoMedico = txtApellidoMedico.getText();
        if (apellidoMedico.isEmpty()) {
            apellidoMedico = null;
        }
        System.out.println(" 1:"+apellidoMedico);
        if(cboEspecialidad.getSelectedIndex()== 0){
            especialidad = null;
        }else{
            especialidad = cboEspecialidad.getSelectedItem().toString();
        }
        
        LocalDate fecha = dpFecha.getDate();
        LocalTime hora = tpHora.getTime();
        List<ListaHorarioCita> todosLosHorarios = controlador.buscarHorariosMedicos(null,apellidoMedico,especialidad,fecha,hora);
        cargarDatosTabla(todosLosHorarios);
        System.out.print(" 1:"+apellidoMedico+" 2:"+especialidad+" 3:"+fecha+" 4:"+hora);
    }//GEN-LAST:event_btnBuscarMedicoActionPerformed

    private void btnRegistarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarCitaActionPerformed
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        int filaSeleccionada = TablaHorarioCita.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila de la tabla.");
            return; // Salimos del método para que no continúe
        }
        
        try {
            int idPaciente = Integer.parseInt(txtIdPaciente.getText());
            int idMedico = Integer.parseInt(TablaHorarioCita.getValueAt(filaSeleccionada, 0).toString());
            LocalDateTime hora_inicio = LocalDateTime.parse(TablaHorarioCita.getValueAt(filaSeleccionada, 5).toString(), formateador);
            LocalDateTime hora_fin = LocalDateTime.parse(TablaHorarioCita.getValueAt(filaSeleccionada, 6).toString(), formateador);
            
            System.out.println(hora_inicio+"");
            System.out.println(hora_fin+"");
            String motivo = (txtAreaMotivo.getText() != null) ? txtAreaMotivo.getText() : "";
            int idUsuario = 1;
            
            int resultado = controlador.RegistrarCita(idPaciente,idMedico, hora_inicio, hora_fin, motivo,idUsuario);
            
            if (resultado > 0) {
                JOptionPane.showMessageDialog(
                    this,
                    "Registro realizado exitosamente para el médico ID: " + idMedico,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
                
                LimpiarPaciente();
                LimpiarHorario();
                
                try {
                    //SECCION DE TWILIO
                    CitaDAO citaDAO = new CitaDAO();
                    CitaNotificacion cita = citaDAO.obtenerDatosCitaParaNotificacion(resultado);
                    
                    String telefono = cita.getTelefono();
                    String paciente = cita.getPaciente();
                    String medico = cita.getMedico();
                    String especialidad = cita.getEspecialidad();
                    String fecha = cita.getFecha();
                    String hora = cita.getHora();

                    // Llamada directa
                    TwilioService.enviarMensaje(
                        telefono, 
                        paciente, 
                        medico, 
                        especialidad, 
                        fecha, 
                        hora
                    );

                    JOptionPane.showMessageDialog(this, "Notificación enviada por WhatsApp al paciente.");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error al enviar WhatsApp: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar la cita",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (NullPointerException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "La fila seleccionada contiene celdas vacías.");
        }
    }//GEN-LAST:event_btnRegistarCitaActionPerformed
    
    public String obtenerTextoDelGrupo(ButtonGroup grupo) {
        Enumeration<AbstractButton> botones = grupo.getElements();
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.isSelected()) {
                return boton.getText();
            }
        }
        return ""; // Ninguno seleccionado
    }
    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Validar campos obligatorios
            if (txtNombrePaciente.getText().trim().isEmpty() || 
                txtApellidoPaciente.getText().trim().isEmpty() || 
                txtDNI.getText().trim().isEmpty() || 
                txtFechaNacimiento.getText().trim().isEmpty() ||
                btnGroupDoc.getSelection() == null ||
                btnGroupGenero.getSelection() == null) {

                JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Parsear la fecha desde el JTextField (dd/MM/yyyy) a LocalDate
            LocalDate fechaNacimiento = txtFechaNacimiento.getDate();
            //txtTipoDoc.getText().trim()
            //txtGenero.getText().trim()
            String tipoDoc = obtenerTextoDelGrupo(btnGroupDoc);
            String genero = obtenerTextoDelGrupo(btnGroupGenero);
            // 3. Llamar al controlador para registrar
            boolean exito = controladorPaciente.registrarPaciente(
                txtNombrePaciente.getText().trim(),
                txtApellidoPaciente.getText().trim(),
                tipoDoc,
                txtDNI.getText().trim(),
                fechaNacimiento,
                genero,
                txtTelefono.getText().trim(),
                txtEmail.getText().trim(),
                txtDireccion.getText().trim()
            );

            // 4. Mostrar respuesta y limpiar formulario
            if (exito) {
                JOptionPane.showMessageDialog(this, "Paciente registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                //limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el paciente. Verifique si el documento ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use el formato dd/MM/yyyy.", "Error de Fecha", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void btnActualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPacienteActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validar que exista un ID seleccionado para editar
            if (txtIdPaciente.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Primero debe buscar o seleccionar un paciente para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idPaciente = Integer.parseInt(txtIdPaciente.getText().trim());
            LocalDate fechaNacimiento = txtFechaNacimiento.getDate();
            String tipoDoc = obtenerTextoDelGrupo(btnGroupDoc);
            String genero = obtenerTextoDelGrupo(btnGroupGenero);
            // 2. Llamar al controlador para actualizar
            boolean exito = controladorPaciente.actualizarPaciente(
                idPaciente,
                txtNombrePaciente.getText().trim(),
                txtApellidoPaciente.getText().trim(),
                tipoDoc,
                txtDNI.getText().trim(),
                fechaNacimiento,
                genero,
                txtTelefono.getText().trim(),
                txtEmail.getText().trim(),
                txtDireccion.getText().trim()
            );

            // 3. Mostrar respuesta y limpiar
            if (exito) {
                JOptionPane.showMessageDialog(this, "Datos del paciente actualizados correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                LimpiarPaciente();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar la información del paciente.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use el formato dd/MM/yyyy.", "Error de Fecha", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del paciente no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarPacienteActionPerformed
    
    private void LimpiarPaciente(){
        txtIdPaciente.setText(null);
        txtNombrePaciente.setText(null);
        txtApellidoPaciente.setText(null);
        txtDNI.setText(null);
        txtTelefono.setText(null);
        txtFechaNacimiento.setDate(null);
        txtEmail.setText(null);
        txtDireccion.setText(null);
        txtAreaMotivo.setText(null);
    }
    
    private void LimpiarHorario(){
        txtApellidoMedico.setText(null);
        cboEspecialidad.setSelectedIndex(0);
        dpFecha.setDate(null);
        tpHora.setTime(null);
    }
    
    private void btnLimpiarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarHorarioActionPerformed
        // TODO add your handling code here:
        LimpiarHorario();
    }//GEN-LAST:event_btnLimpiarHorarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LimpiarPaciente();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmSolicitar_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmSolicitar_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmSolicitar_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmSolicitar_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSolicitar_citas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaHorarioCita;
    private javax.swing.JButton btnActualizarPaciente;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarMedico;
    private javax.swing.ButtonGroup btnGroupDoc;
    private javax.swing.ButtonGroup btnGroupGenero;
    private javax.swing.JButton btnLimpiarHorario;
    private javax.swing.JButton btnRegistarCita;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JComboBox<String> cboEspecialidad;
    private com.github.lgooddatepicker.components.DatePicker dpFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblid_usuario;
    private javax.swing.JRadioButton rbCE;
    private javax.swing.JRadioButton rbDni;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private com.github.lgooddatepicker.components.TimePicker tpHora;
    private javax.swing.JTextField txtApellidoMedico;
    private javax.swing.JTextField txtApellidoPaciente;
    private javax.swing.JTextArea txtAreaMotivo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private com.github.lgooddatepicker.components.DatePicker txtFechaNacimiento;
    private javax.swing.JTextField txtIdPaciente;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
