package Formularios;

import Controler.ControladorTriaje;
import Model.Paciente;
import java.sql.*;
import java.util.List;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class FrmTriaje extends javax.swing.JFrame {
    
    ControladorTriaje controlador = new ControladorTriaje();
    /**
     * Creates new form FrmConsulta_Medica
     */
    public FrmTriaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        txtPresion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSaturacion = new javax.swing.JTextField();
        txtAreaNota = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNacimiento = new javax.swing.JTextField();
        btnTriaje = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCita = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtCita = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtFrecuencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Presion (mmHg)");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));
        getContentPane().add(txtPresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 130, -1));

        jLabel14.setText("Temperatura C°");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));
        getContentPane().add(txtTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 130, -1));
        getContentPane().add(txtTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 130, -1));

        jLabel6.setText("Talla (cm)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabel5.setText("Peso (kg)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));
        getContentPane().add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 130, -1));

        jLabel7.setText("Saturacion (%)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));
        getContentPane().add(txtSaturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 130, -1));
        getContentPane().add(txtAreaNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 270, 80));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Notas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel2.setText("Nombre Completo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setFocusable(false);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, -1));

        txtDocumento.setEditable(false);
        txtDocumento.setBackground(new java.awt.Color(204, 204, 204));
        txtDocumento.setFocusable(false);
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, -1));

        jLabel3.setText("Numero Documento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setText("Sexo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtNacimiento.setEditable(false);
        txtNacimiento.setBackground(new java.awt.Color(204, 204, 204));
        txtNacimiento.setFocusable(false);
        getContentPane().add(txtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, -1));

        btnTriaje.setBackground(new java.awt.Color(0, 204, 0));
        btnTriaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTriaje.setText("Guardar Triaje");
        btnTriaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriajeActionPerformed(evt);
            }
        });
        getContentPane().add(btnTriaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 40));

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 255));
        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 110, 40));

        jLabel1.setText("N° CITA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnCita.setBackground(new java.awt.Color(0, 204, 204));
        btnCita.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCita.setText("Buscar Cita");
        btnCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, -1));

        jLabel8.setText("Fecha Nacimiento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(txtCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, -1));

        txtSexo.setEditable(false);
        txtSexo.setBackground(new java.awt.Color(204, 204, 204));
        txtSexo.setFocusable(false);
        getContentPane().add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 140, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea1.setFocusable(false);
        getContentPane().add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 330, 180));

        jLabel9.setText("Frecuencia (lpm)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));
        getContentPane().add(txtFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 130, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Triaje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextArea2.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 280, 230));

        jLabel10.setText("FORMULARIO TRIAJE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Limpiar(){
        txtCita.setText("");
        txtNombre.setText("");
        txtDocumento.setText("");
        txtSexo.setText("");
        txtPeso.setText("");
        txtTalla.setText("");
        txtTemp.setText("");
        txtPresion.setText("");
        txtFrecuencia.setText("");
        txtSaturacion.setText("");
        txtAreaNota.setText("");
    }
    
    private void btnCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitaActionPerformed
        // TODO add your handling code here:
        List<Paciente> pacientes = controlador.listarDatosPaciente(Integer.parseInt(txtCita.getText()));
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        if (pacientes != null && !pacientes.isEmpty()) {
            Paciente paciente = pacientes.get(0);
            
            txtNombre.setText(paciente.getNombre());
            txtDocumento.setText(paciente.getNumero_documento());
            txtSexo.setText(paciente.getGenero());
            txtNacimiento.setText(paciente.getFecha_nacimiento().format(formatter));
        } else {
            // Si la lista está vacía, avisar al usuario a limpiar los campos
            JOptionPane.showMessageDialog(null, "No se encontraron horarios para el apellido ingresado.");
        }
    }//GEN-LAST:event_btnCitaActionPerformed

    private void btnTriajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriajeActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(
            null, 
            "¿Estás seguro de que deseas continuar?", 
            "Confirmación", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (respuesta == JOptionPane.YES_OPTION){
            int idCita = Integer.parseInt(txtCita.getText());
            double peso_kg=Double.parseDouble(txtPeso.getText());
            double talla=Double.parseDouble(txtTalla.getText());
            double temperatura=Double.parseDouble(txtTemp.getText());
            String presion=txtPresion.getText();
            int frecuencia=Integer.parseInt(txtFrecuencia.getText());
            int saturacion=Integer.parseInt(txtSaturacion.getText());
            String notas=txtAreaNota.getText();

            boolean resultado = controlador.ActualizarTriaje(idCita, peso_kg, talla, temperatura, presion, frecuencia, saturacion, notas);

            if (resultado) {
                JOptionPane.showMessageDialog(
                    this,
                    "Triaje realizado exitosamente para la cita ID: " + idCita,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
                Limpiar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar el Triaje",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }else {
            JOptionPane.showMessageDialog(null, "Acción cancelada.");
        }      
    }//GEN-LAST:event_btnTriajeActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTriaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTriaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTriaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTriaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTriaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCita;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTriaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtAreaNota;
    private javax.swing.JTextField txtCita;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPresion;
    private javax.swing.JTextField txtSaturacion;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
